### ISSUE TITLE
1.0.1 issues

### ISSUE THREAD

**Issue by NathanSweet** [libgdx/gdx-particle-editor#2]
Hola! I thought it'd be better to post here rather than [there](https://github.com/libgdx/libgdx/issues/7285).

I took 1.0.1 for a quick spin:

* Click spinner up/down without moving the mouse: value changes until mouse moved. Does not occur for press and hold.
  * I use a trackball (Kensington Expert Mouse master race), so it's very easy to click without moving the mouse at all. I highly recommend the Expert Mouse (and Imak SmartGlove w/ Thumb, code like a ninja and save your wrists at the _same time_).
* Double click up/down no longer goes up forever (only until mouse is moved, like single click).
* Just noticed the spinner drag bar, nice! Good discoverability.
* Clicking an existing tint handle adds a new one on top of it.
* Double click a tint handle: 2 color dialogs appear and only one can be closed, need to restart the app.

**Comment by raeleus** [comment]
Thank you very much for following up on this. I suspect that you have a driver/hardware issue with your mouse that causes it to send two touch-downs instead of just one. You can [test that here](https://doubleclicktest.com/) if you're interested. You should get 0 "Double Clicks" with a normally functioning mouse. Nevertheless, it's a good idea to harden the widgets against this sort of thing anyway.
Can you try the attached updated JAR? It should solve these issues.
[gdx-particle-editor.zip](https://github.com/libgdx/gdx-particle-editor/files/13466092/gdx-particle-editor.zip)
And thanks for noticing the drag bars. I took inspiration from Spine on that one 😉

**Comment by NathanSweet** [comment]
How DARE you suggest my wonderful mouse has a malfunction!? I'd surely have noticed in Spine development. Clicking normally on that test page I get 0 double clicks.

You zipped a JAR? :p Trying that JAR:

* Clicking without moving the mouse the value goes up by 1, then by 10. Eg, 32 -> 33 then a moment later 43. At least it doesn't run away to infinity and beyond!
* Click to create a tint handle, click to edit it, escape to close the color dialog, clicking the handle again does nothing until I mouse off the handle. Maybe it's not important.
* Click to create a tint handle, click to edit it, escape to close the color dialog, double click: a new handle is created.
* Double click doesn't delete tint handles. If the mouse is not centered exactly, the handle moves.

**Comment by raeleus** [comment]
Sorry, Nate. I'm totally at a loss on this one. I only mentioned the double click thing because I had that problem with an old mouse. Maybe I have to buy one of those trackballs to see what's going on. Perhaps this was all a ruse to get me to see the light ehh?
I feel like I have to refactor these classes completely. I'll give it another try this weekend. It's just so perplexing to me. It's only touch downs and touch ups. Thanks again.

**Comment by NathanSweet** [comment]
As much as I love the trackball (it has a scroll ring around the ball! a ball ring, if you will) I doubt it's hardware specific. I can't explain why you can't repro, except possibly that with an old fashioned arthritic mouse it's easy to move 1px and wreck the repro.

I [see](https://github.com/libgdx/gdx-particle-editor/blob/master/core/src/main/java/com/ray3k/stripe/Spinner.java#L217-L238) the InputListener returns false in `touchDown`. Per the javadoc, true must be returned for `touchUp` to be called. If false is returned, the actor is not added to the Stage's `touchFocuses` and will never receive a `touchUp`.

**Comment by raeleus** [comment]
Ahh, what a rookie mistake. That would explain the behavior in Spinner, but not in ColorGraph and LineGraph. I'll do some more testing.

**Comment by raeleus** [comment]
@NathanSweet, sorry to keep bugging you. I think I've addressed the new issues you pointed out in [1.0.2](https://github.com/libgdx/gdx-particle-editor/releases/tag/1.0.2). I should buy you a beer or something :-)

**Comment by NathanSweet** [comment]
Nah, I'm happy to help. I've confirmed everything looks good now! \o/
